site_name: Docs
site_url: https://docs.monoquant.com
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  logo: logo-white.png
  palette:
    scheme: slate
  favicon: img/favicon.ico
extra_css: [extra_css.css]
nav:
  - Getting Started:
      - 'What is the Strategy Builder?': getting_started/what_is_the_strategy_builder.md
      - 'Building Your First Strategy': getting_started/building_your_first_strategy.md
      - 'Building Your First AI Strategy?': getting_started/building_your_first_ai_strategy.md
      - 'Understanding Backtesting Engine': general_docs/backtesting_engine.md
      - 'Setup Telegram Notifications': getting_started/setup_telegram_notifications.md
      # - 'TODO - Understanding Backtesting Results': getting_started/understanding_backtest_results.md
  - Strategy Builder:
      - 'Strategy Details': strategy_nodes/Strategy_Details.md
      - 'Create Signal': strategy_nodes/Create_Signal.md
      - Non Trading Times': strategy_nodes/Non_Trading_Times.md
#     - 'Position Data Point': strategy_nodes/Position_Data_Point.md
      - 'Scale in': strategy_nodes/Scale_In.md
      - 'Signal Group': strategy_nodes/Signal_Group.md
      - 'Take Profit': strategy_nodes/Take_Profit.md
      - 'Trailing Take Profit': strategy_nodes/Trailing_Take_Profit.md
      - 'AI Models': data_nodes/AI_Models.md
      - 'Arithmetic Data Points': data_nodes/Arithmetic_Data_Point.md
      - 'Data Point': data_nodes/Data_Point.md
      - 'Stat Data Point': data_nodes/Stat_Data_Point.md
      - 'TA Datapoint': data_nodes/TA_Data_Point.md
      # - 'TODO - Community Data Point': data_nodes/Community_Data_Point.md
  # - Trading Terminal:
  #     - 'TODO - Overview': trading_terminal/trading_terminal_overview.md
  #     - 'TODO - Settings': trading_terminal/trading_terminal_settings.md
  #     - 'TODO - Interface': trading_terminal/trading_terminal_interface.md
  #     - 'TODO - Trading': trading_terminal/trading_terminal_trading.md
  #     - 'TODO - Orders': trading_terminal/trading_terminal_orders.md
  # - Live Trading:
  #     - 'TODO - Putting a Strategy Live': 
  - Paper Trading:
      - 'Paper Trading Overview': paper_trading/paper_trading_overview.md
  # - TODO - Social Trading: social_trading/social_trading_overview.md
  - $MONQ:
      - 'What is MONQ?': monq/what_is_monq.md
      - 'Tokenomics': monq/tokenomics.md
      - 'Staking': monq/staking.md
      - 'Achievements': monq/achievements.md
      - 'Sponsored Trading Competitions': monq/sponsored_trading.md
      # - 'TODO - Copy Trading': monq/copy_trading.md
      - 'Monq Market': monq/monq_market.md
  - Roadmap: roadmap.md





