name: Monoquant Docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      run: echo "IMAGE_TAG=ghcr.io/${{ github.repository }}/main/monoquant-docs:$(date +%s)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: docker build . --file ./.github/docker/docs.dockerfile --tag $IMAGE_TAG --build-arg GH_PAT=${{ secrets.GH_PAT }}

    - name: Push the Docker image
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: docker push $IMAGE_TAG
