name: Monoquant Docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      run: echo "IMAGE_TAG=ghcr.io/${{ github.repository }}/main/monoquant-docs:$(date +%s)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.github/docker/monoquant-systems.dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ env.IMAGE_TAG }}
        build-args: |
          GH_PAT=${{ secrets.GH_PAT }}
#        no-cache: true

    - name: Push the Docker image
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: docker push $IMAGE_TAG

    - name: Retag image with latest
      run: |
        docker tag ${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/main/monoquant-docs:latest

    - name: Push the latest tag
      run: |
        docker push ghcr.io/${{ github.repository }}/main/monoquant-docs:latest